# Generated by Django 5.2.17 on 2026-09-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Імʼя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('property_type', models.CharField(max_length=80, verbose_name='Тип приміщення')),
                ('area', models.CharField(max_length=20, verbose_name='Площа')),
                ('cleaning_type', models.CharField(max_length=80, verbose_name='Вид прибирання')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.CharField(max_length=40, verbose_name='Час')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Надіслано в Telegram')),
                ('telegram_error', models.TextField(blank=True, verbose_name='Помилка Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Замовте прибирання за 2 хвилини', max_length=255, verbose_name='Заголовок')),
                ('step_contacts', models.CharField(default='Контакти', max_length=40, verbose_name='Крок 1')),
                ('step_object', models.CharField(default='Обʼєкт', max_length=40, verbose_name='Крок 2')),
                ('step_details', models.CharField(default='Деталі', max_length=40, verbose_name='Крок 3')),
                ('name_label', models.CharField(default='Імʼя', max_length=80, verbose_name='Імʼя: підпис')),
                ('name_placeholder', models.CharField(default='Ваше імʼя', max_length=80, verbose_name='Імʼя: плейсхолдер')),
                ('phone_label', models.CharField(default='Телефон', max_length=80, verbose_name='Телефон: підпис')),
                ('phone_placeholder', models.CharField(default='+380 XX XXX XX XX', max_length=80, verbose_name='Телефон: плейсхолдер')),
                ('email_label', models.CharField(default='Email', max_length=80, verbose_name='Email: підпис')),
                ('email_placeholder', models.CharField(default='email@example.com', max_length=80, verbose_name='Email: плейсхолдер')),
                ('address_label', models.CharField(default='Адреса', max_length=80, verbose_name='Адреса: підпис')),
                ('address_placeholder', models.CharField(default='Вулиця, будинок, квартира', max_length=120, verbose_name='Адреса: плейсхолдер')),
                ('property_type_label', models.CharField(default='Тип приміщення', max_length=80, verbose_name='Тип приміщення: підпис')),
                ('property_type_placeholder', models.CharField(default='Оберіть тип', max_length=80, verbose_name='Тип приміщення: плейсхолдер')),
                ('area_label', models.CharField(default='Площа (м²)', max_length=80, verbose_name='Площа: підпис')),
                ('area_placeholder', models.CharField(default='Наприклад, 65', max_length=80, verbose_name='Площа: плейсхолдер')),
                ('cleaning_type_label', models.CharField(default='Вид прибирання', max_length=80, verbose_name='Вид прибирання: підпис')),
                ('cleaning_type_placeholder', models.CharField(default='Оберіть вид', max_length=80, verbose_name='Вид прибирання: плейсхолдер')),
                ('date_label', models.CharField(default='Бажана дата', max_length=80, verbose_name='Дата: підпис')),
                ('time_label', models.CharField(default='Бажаний час', max_length=80, verbose_name='Час: підпис')),
                ('time_placeholder', models.CharField(default='Оберіть час', max_length=80, verbose_name='Час: плейсхолдер')),
                ('comment_label', models.CharField(default='Коментар', max_length=80, verbose_name='Коментар: підпис')),
                ('comment_placeholder', models.CharField(default='Додаткові побажання або особливості обʼєкта', max_length=255, verbose_name='Коментар: плейсхолдер')),
                ('photos_label', models.CharField(default='Завантажити фотографії', max_length=80, verbose_name='Фото: підпис')),
                ('photos_hint', models.CharField(default='Натисніть або перетягніть файли сюди', max_length=255, verbose_name='Фото: підказка')),
                ('photos_note', models.CharField(default='PNG, JPG до 10 МБ', max_length=120, verbose_name='Фото: формат')),
                ('back_text', models.CharField(default='Назад', max_length=40, verbose_name='Кнопка «Назад»')),
                ('next_text', models.CharField(default='Далі', max_length=40, verbose_name='Кнопка «Далі»')),
                ('submit_text', models.CharField(default='Замовити прибирання', max_length=80, verbose_name='Кнопка відправки')),
                ('success_title', models.CharField(default='Заявку надіслано!', max_length=160, verbose_name='Успіх: заголовок')),
                ('success_text', models.TextField(default='Дякуємо, {name}. Менеджер звʼяжеться з вами протягом 15 хвилин для підтвердження деталей.', help_text='Можна використати {name}', verbose_name='Успіх: текст')),
            ],
            options={
                'verbose_name': 'Форма замовлення',
                'verbose_name_plural': 'Форма замовлення',
            },
        ),
        migrations.CreateModel(
            name='CleaningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=80, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Вид прибирання',
                'verbose_name_plural': 'Види прибирання',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('label', models.CharField(max_length=80, verbose_name='Підпис')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
                ('href', models.CharField(blank=True, max_length=255, verbose_name='Посилання')),
                ('tint', models.CharField(choices=[('peach', 'peach'), ('sage', 'sage'), ('lavender', 'lavender'), ('sky', 'sky')], default='peach', max_length=20, verbose_name='Колір')),
            ],
            options={
                'verbose_name': 'Картка контакту',
                'verbose_name_plural': 'Картки контактів',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контакти', max_length=255, verbose_name='Заголовок')),
                ('map_embed_url', models.TextField(blank=True, verbose_name='URL карти (iframe)')),
                ('map_title', models.CharField(blank=True, max_length=160, verbose_name='Title карти')),
            ],
            options={
                'verbose_name': 'Секція контактів',
                'verbose_name_plural': 'Секція контактів',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.CharField(max_length=255, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Часті запитання', max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Секція FAQ',
                'verbose_name_plural': 'Секція FAQ',
            },
        ),
        migrations.CreateModel(
            name='FooterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=120, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Послуга у футері',
                'verbose_name_plural': 'Послуги у футері',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=255, verbose_name='Надзаголовок')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Підзаголовок')),
                ('primary_cta_text', models.CharField(default='Замовити прибирання', max_length=80, verbose_name='Основна кнопка')),
                ('primary_cta_href', models.CharField(default='#booking', max_length=120, verbose_name='URL основної кнопки')),
                ('secondary_cta_text', models.CharField(default='Подивитись роботи', max_length=80, verbose_name='Друга кнопка')),
                ('secondary_cta_href', models.CharField(default='#portfolio', max_length=120, verbose_name='URL другої кнопки')),
                ('image', models.ImageField(blank=True, upload_to='hero/', verbose_name='Фото')),
                ('image_url', models.URLField(blank=True, verbose_name='Фото (URL)')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Alt фото')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Підпис під фото')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Hero',
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('href', models.CharField(max_length=120, verbose_name='Якір / URL')),
                ('label', models.CharField(max_length=80, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Категорія портфоліо',
                'verbose_name_plural': 'Категорії портфоліо',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наші роботи', max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Підзаголовок')),
                ('all_category_label', models.CharField(default='Усі', max_length=40, verbose_name='Мітка «Усі»')),
            ],
            options={
                'verbose_name': 'Секція портфоліо',
                'verbose_name_plural': 'Секція портфоліо',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=80, verbose_name='Назва')),
                ('price', models.CharField(max_length=40, verbose_name='Ціна')),
                ('unit', models.CharField(default='грн', max_length=20, verbose_name='Одиниця')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('highlighted', models.BooleanField(default=False, verbose_name='Виділений')),
                ('cta_text', models.CharField(default='Замовити', max_length=80, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифи',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ціни', max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Підзаголовок')),
            ],
            options={
                'verbose_name': 'Секція цін',
                'verbose_name_plural': 'Секція цін',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=80, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Тип приміщення',
                'verbose_name_plural': 'Типи приміщень',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description')),
                ('robots', models.CharField(blank=True, default='index, follow', max_length=120, verbose_name='Robots')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='OG title')),
                ('og_description', models.TextField(blank=True, verbose_name='OG description')),
                ('og_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='OG image')),
                ('og_image_url', models.URLField(blank=True, verbose_name='OG image URL')),
                ('og_type', models.CharField(blank=True, default='website', max_length=50, verbose_name='OG type')),
                ('og_locale', models.CharField(blank=True, default='uk_UA', max_length=20, verbose_name='OG locale')),
                ('twitter_card', models.CharField(blank=True, default='summary_large_image', max_length=50, verbose_name='Twitter card')),
                ('twitter_title', models.CharField(blank=True, max_length=255, verbose_name='Twitter title')),
                ('twitter_description', models.TextField(blank=True, verbose_name='Twitter description')),
                ('twitter_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='Twitter image')),
                ('twitter_image_url', models.URLField(blank=True, verbose_name='Twitter image URL')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=160, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Фото')),
                ('image_url', models.URLField(blank=True, verbose_name='Фото (URL)')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Послуги', max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Підзаголовок')),
            ],
            options={
                'verbose_name': 'Секція послуг',
                'verbose_name_plural': 'Секція послуг',
            },
        ),
        migrations.CreateModel(
            name='SiteChrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_primary', models.CharField(default='Блиск', max_length=80, verbose_name='Бренд (перша частина)')),
                ('brand_accent', models.CharField(default='клінінг', max_length=80, verbose_name='Бренд (акцент)')),
                ('header_cta_text', models.CharField(default='Замовити прибирання', max_length=80, verbose_name='Кнопка в шапці')),
                ('floating_button_text', models.CharField(default='Замовити', max_length=80, verbose_name='Плаваюча кнопка')),
                ('footer_tagline', models.TextField(blank=True, verbose_name='Текст у футері')),
                ('footer_nav_title', models.CharField(default='Навігація', max_length=80, verbose_name='Заголовок навігації у футері')),
                ('footer_services_title', models.CharField(default='Послуги', max_length=80, verbose_name='Заголовок послуг у футері')),
                ('copyright_name', models.CharField(default='Блиск Клінінг', max_length=120, verbose_name='Назва в copyright')),
                ('privacy_label', models.CharField(default='Конфіденційність', max_length=80, verbose_name='Посилання: конфіденційність')),
                ('privacy_url', models.CharField(blank=True, default='#', max_length=255, verbose_name='URL конфіденційності')),
                ('terms_label', models.CharField(default='Умови', max_length=80, verbose_name='Посилання: умови')),
                ('terms_url', models.CharField(blank=True, default='#', max_length=255, verbose_name='URL умов')),
            ],
            options={
                'verbose_name': 'Шапка і футер',
                'verbose_name_plural': 'Шапка і футер',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=80, verbose_name='Назва')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Соцмережа',
                'verbose_name_plural': 'Соцмережі',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('value', models.FloatField(verbose_name='Число')),
                ('suffix', models.CharField(blank=True, max_length=20, verbose_name='Суфікс')),
                ('label', models.CharField(max_length=80, verbose_name='Підпис')),
                ('decimals', models.PositiveSmallIntegerField(default=0, verbose_name='Знаків після коми')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Увімкнено')),
                ('bot_token', models.CharField(blank=True, max_length=255, verbose_name='Токен бота')),
                ('chat_id', models.CharField(blank=True, max_length=64, verbose_name='Chat ID')),
            ],
            options={
                'verbose_name': 'Telegram',
                'verbose_name_plural': 'Telegram',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=120, verbose_name='Імʼя')),
                ('role', models.CharField(blank=True, max_length=160, verbose_name='Роль')),
                ('text', models.TextField(verbose_name='Текст')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оцінка')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Відгуки клієнтів', max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Секція відгуків',
                'verbose_name_plural': 'Секція відгуків',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('label', models.CharField(max_length=40, verbose_name='Інтервал')),
            ],
            options={
                'verbose_name': 'Часовий слот',
                'verbose_name_plural': 'Часові слоти',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Бейдж довіри',
                'verbose_name_plural': 'Бейджі довіри',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('thumbnail', models.ImageField(blank=True, upload_to='videos/thumbs/', verbose_name='Превʼю')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Превʼю (URL)')),
                ('video', models.FileField(blank=True, upload_to='videos/', verbose_name='Відеофайл')),
                ('video_url', models.URLField(blank=True, verbose_name='Відео (YouTube / Vimeo / MP4 URL)')),
            ],
            options={
                'verbose_name': 'Відео',
                'verbose_name_plural': 'Відео',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideosSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Як ми працюємо', max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Секція відео',
                'verbose_name_plural': 'Секція відео',
            },
        ),
        migrations.CreateModel(
            name='WhyUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Чому нас обирають', max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Підзаголовок')),
            ],
            options={
                'verbose_name': 'Секція «Чому ми»',
                'verbose_name_plural': 'Секція «Чому ми»',
            },
        ),
        migrations.CreateModel(
            name='BookingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bookings/', verbose_name='Фото')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cms.booking', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Фото заявки',
                'verbose_name_plural': 'Фото заявок',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('before_image', models.ImageField(blank=True, upload_to='portfolio/before/', verbose_name='До')),
                ('before_image_url', models.URLField(blank=True, verbose_name='До (URL)')),
                ('after_image', models.ImageField(blank=True, upload_to='portfolio/after/', verbose_name='Після')),
                ('after_image_url', models.URLField(blank=True, verbose_name='Після (URL)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cms.portfoliocategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Робота',
                'verbose_name_plural': 'Портфоліо',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.CharField(max_length=255, verbose_name='Пункт')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cms.pricingplan', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Пункт тарифу',
                'verbose_name_plural': 'Пункти тарифів',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
