# Generated by Django 5.2.17 on 2026-09-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Категорія «До і після»', 'verbose_name_plural': 'Категорії «До і після»'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'До і після', 'verbose_name_plural': 'До і після'},
        ),
        migrations.AlterModelOptions(
            name='portfoliosection',
            options={'verbose_name': 'До і після', 'verbose_name_plural': 'До і після'},
        ),
        migrations.AddField(
            model_name='portfoliosection',
            name='after_label',
            field=models.CharField(default='Після', max_length=40, verbose_name='Підпис «Після»'),
        ),
        migrations.AddField(
            model_name='portfoliosection',
            name='before_label',
            field=models.CharField(default='До', max_length=40, verbose_name='Підпис «До»'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='after_image',
            field=models.ImageField(blank=True, upload_to='portfolio/after/', verbose_name='Фото «Після»'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='after_image_url',
            field=models.URLField(blank=True, verbose_name='Фото «Після» (URL)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='before_image',
            field=models.ImageField(blank=True, upload_to='portfolio/before/', verbose_name='Фото «До»'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='before_image_url',
            field=models.URLField(blank=True, verbose_name='Фото «До» (URL)'),
        ),
        migrations.AlterField(
            model_name='portfoliosection',
            name='title',
            field=models.CharField(default='До і після', max_length=255, verbose_name='Заголовок'),
        ),
    ]
