# Generated by Django 5.2.17 on 2026-09-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_portfoliocategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Фото «До і після»', 'verbose_name_plural': 'Фото «До і після»'},
        ),
        migrations.AlterModelOptions(
            name='portfoliosection',
            options={'verbose_name': 'Налаштування блоку «До і після»', 'verbose_name_plural': 'Налаштування блоку «До і після»'},
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Завантажте фото після прибирання', upload_to='portfolio/after/', verbose_name='Фото «Після»'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='after_image_url',
            field=models.URLField(blank=True, verbose_name='Або URL фото «Після»'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Завантажте фото до прибирання', upload_to='portfolio/before/', verbose_name='Фото «До»'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='before_image_url',
            field=models.URLField(blank=True, verbose_name='Або URL фото «До»'),
        ),
    ]
