# Generated by Django 5.2.17 on 2026-09-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_deploy_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitechrome',
            name='brand_accent',
            field=models.CharField(default='clean', max_length=80, verbose_name='Бренд (акцент)'),
        ),
        migrations.AlterField(
            model_name='sitechrome',
            name='brand_primary',
            field=models.CharField(default='AS', max_length=80, verbose_name='Бренд (перша частина)'),
        ),
        migrations.AlterField(
            model_name='sitechrome',
            name='copyright_name',
            field=models.CharField(default='AS clean', max_length=120, verbose_name='Назва в copyright'),
        ),
    ]
