# Generated by Django 5.2.17 on 2026-09-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_sitechrome_brand_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_hero', models.BooleanField(default=True, verbose_name='Hero')),
                ('show_services', models.BooleanField(default=False, verbose_name='Послуги')),
                ('show_why_us', models.BooleanField(default=False, verbose_name='Чому ми / про компанію')),
                ('show_stats', models.BooleanField(default=False, verbose_name='Статистика')),
                ('show_portfolio', models.BooleanField(default=False, verbose_name='До і після')),
                ('show_videos', models.BooleanField(default=False, verbose_name='Відео')),
                ('show_pricing', models.BooleanField(default=False, verbose_name='Ціни')),
                ('show_testimonials', models.BooleanField(default=False, verbose_name='Відгуки')),
                ('show_faq', models.BooleanField(default=False, verbose_name='FAQ')),
                ('show_booking', models.BooleanField(default=True, verbose_name='Форма замовлення')),
                ('show_contact', models.BooleanField(default=True, verbose_name='Контакти')),
            ],
            options={
                'verbose_name': 'Видимість секцій',
                'verbose_name_plural': 'Видимість секцій',
            },
        ),
    ]
