# Generated by Django 5.2.17 on 2026-09-26 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_section_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.videossection', verbose_name='Секція'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 / WebM, бажано до 80 МБ', upload_to='videos/', verbose_name='Відеофайл'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo або прямий URL на MP4', verbose_name='Або посилання на відео'),
        ),
    ]
